.\" Copyright (c) 2012 Ryan Flannery <ryan.flannery@gmail.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt VITUNES-INIT 1
.Os
.Sh NAME
.Nm vitunes-init
.Nd initialize the media database
.Sh SYNOPSIS
.Bk -words
.Nm vitunes -e init
.Ek
.Sh DESCRIPTION
The
.Ic init
e-command is used to setup the initial files and directories used by
.Xr vitunes 1 ,
and must be run once.
Running it additional times will have no affect.
.Pp
The database created is initially empty, and files must be added before
.Nm
can be run normally.
See
.Xr vitunes-add 1
for instructions on doing this.
.Pp
It is not strictly necessary to run this e-command to start using
.Xr vitunes 1 ,
since an existing installation could be used or the files created by hand.
It is provided for convenience.
.Sh FILES
.Bl -tag -width Ds -compact
.It Pa ~/.vitunes
The
.Xr vitunes 1
core directory where everything is stored.
.It Pa ~/.vitunes/playlists
The directory where all playlists are stored.
This can be overridden with the
.Op Fl p Ar playlist-dir
flag.
.It Pa ~/.vitunes/vitunes.db
The library database containing the meta-information of all media files.
This can be overridden with the
.Op Fl d Ar database-file
flag.
.El
.Sh EXAMPLES
As the
.Ic init
e-command takes no arguments, it's only usage is the following:
.Pp
.Dl $ vitunes -e init
.Sh SEE ALSO
.Xr vitunes 1 ,
.Xr vitunes-add 1
.Sh AUTHORS
.An Ryan Flannery Aq Mt ryan.flannery@gmail.com .
