.\" Copyright (c) 2012 Ryan Flannery <ryan.flannery@gmail.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: August 3 2010 $
.Dt VITUNES-RM 1
.Os
.Sh NAME
.Nm vitunes-rm
.Nd remove a file or a URL from the database
.Sh SYNOPSIS
.Nm vitunes -e rm
.Bk -words
.Op Fl f
.Ar URL | path
.Ek
.Sh DESCRIPTION
To remove a single file
or
.Ar URL
from the
.Xr vitunes 1
database, the
.Ic rm
e-command may be used.
.Pp
Normally, a prompt is shown as a safety measure.
This prompt can be avoided using the
.Fl f
flag, to force the removal.
.Pp
Note that to remove files, the full, absolute path to the file must be
provided, as obtained from
.Xr realpath 3 .
.Sh EXAMPLES
To remove a single file from the
.Xr vitunes 1
database, use:
.Pp
.Dl $ vitunes -e rm /path/to/file.mp3
.Pp
To remove a URL, such as that for an Internet radio stream, use:
.Pp
.Dl $ vitunes -e rm -f \&"http://198.234.121.118/listen.pls"
.Sh SEE ALSO
.Xr vitunes 1 ,
.Xr vitunes-add 1 ,
.Xr realpath 3
.Sh AUTHORS
.An Ryan Flannery Aq Mt ryan.flannery@gmail.com .
