# This file was generated by the 'configure.sh' script on 2012-09-23 at 00:06:45.
# Its contents should probably not be modified directly (if they should,
# please contact the vitunes developers and let them know why).
#
# Generated on: 2012-09-23 at 00:06:45
# Run on OS: Darwin schlipf.local 12.2.0 Darwin Kernel Version 12.2.0: Sat Aug 25 00:48:52 PDT 2012; root:xnu-2050.18.24~1/RELEASE_X86_64 x86_64


# Install Locations
PREFIX?=/usr/local
BINDIR?=/usr/local/bin
MANDIR?=/usr/local/man/man1


# TagLib (empty if TagLib wasn't found)

# taglib library detected by taglib-config
TAGLIB_CFLAGS?=`taglib-config --cflags`
TAGLIB_LDFLAGS?=`taglib-config --libs` -ltag_c



# gstreamer (empty if gstreamer wasn't found)



# configure.sh output ending
