.\" Copyright (c) 2012 Ryan Flannery <ryan.flannery@gmail.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt VITUNES-ADDURL 1
.Os
.Sh NAME
.Nm vitunes-addurl
.Nd add a URL (or non-file playable item) to the database
.Sh SYNOPSIS
.Nm vitunes -e addurl
.Bk -words
.Ar URL | path
.Ek
.Sh DESCRIPTION
To add non-standard files to the
.Xr vitunes 1
database (things like URL's for Internet radio streams), one can use the
.Ic addurl
e-command.
It takes a single parameter: the
.Ar URL
or
.Ar path
to be added to the database.
.Pp
Since meta-information can't be extracted automatically for most URL's,
it needs to be inputted manually.
Fields can be left blank, if wanted.
.Pp
Note that anything
.Xr mplayer 1
or
.Xr gstreamer 3
can play may be added.
To test if a
.Ar URL
is playable by
.Xr mplayer 1 ,
simply try the following, and if it plays, it may be added:
.Dl $ mplayer URL
.Pp
Although regular files could also be added using this e-command, the
.Ic add
e-command is preferred, as it attempts to extract meta-information
automatically.
.Pp
Note that files added to the database using the
.Ic addurl
e-command are
.Sy not
checked for updates during an
.Ic update
e-command.
.Pp
The
.Ic addurl
e-command can also be used to change the meta-information of an
existing
.Ar URL
within the database.
.Sh EXAMPLES
An example of adding an Internet radio stream would look something like
the following:
.Pp
.Dl $ vitunes -e addurl \&"http://198.234.121.118:80"
.Bd -literal -offset indent
Artist: WVXU Online Radio<ENTER>
Album: Cincinnati Public Radio<ENTER>
Title: NPR<ENTER>
Track: <ENTER>
Year: <ENTER>
Genre: Radio<ENTER>
Length: INF<ENTER>
.Ed
.Sh SEE ALSO
.Xr vitunes 1 ,
.Xr vitunes-init 1 ,
.Xr vitunes-add 1
.Sh NOTES
When the
.Xr vitunes 1
database has to be re-built (because of say, an upgrade where the
database format has changed or the database was deleted), re-adding
URL's can be tedious.
To ease this, consider using a shell script like the
.Pa add_urls.sh
file distributed with
.Nm vitunes .
.Sh AUTHORS
.An Ryan Flannery Aq Mt ryan.flannery@gmail.com .
