.\" Copyright (c) 2012 Ryan Flannery <ryan.flannery@gmail.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt VITUNES-CHECK 1
.Os
.Sh NAME
.Nm vitunes-check
.Nd check files for meta-information
.Sh SYNOPSIS
.Nm vitunes -e check
.Bk -words
.Fl d |
.Fl r |
.Fl s
.Ar path
.Op ...
.Ek
.Sh DESCRIPTION
The
.Ic check
e-command will scan each file provided to see if any media
meta-information is present in the file, how
.Xr vitunes-add 1
will sanitize that meta-information (see below), or what information
.Xr vitunes 1
currently has in the database for the file.
.Pp
The options are as follows:
.Bl -tag -width Fl
.It Fl d
Load the
.Xr vitunes 1
database and check to see if each file exists within it.
If so, show the information contained in the database.
.It Fl r
Show the raw information extracted directly from each file.
.It Fl s
Show the sanitized information after extracting it from each file.
See the section
.Sx SANITATION
below for details on what this is.
.El
.Pp
If multiple files are provided, each will be checked in order.
.Sh SANITATION
Some media files have non-printable characters in their meta-information
for one reason or another (often, it's a faulty ripper/tagging
application).
Sometimes these non-printable characters can be control sequences used by
.Xr ncurses 3
and thus cause problems with the display of
.Xr vitunes 1 .
.Pp
To prevent any such problems,
.Xr vitunes-add 1
sanitizes such data by replacing any problematic characters with '?'.
.Sh EXAMPLES
To show raw information from a file:
.Pp
.Dl $ vitunes -e check -r /path/to/file.mp3
.Sh SEE ALSO
.Xr vitunes 1 ,
.Xr vitunes-add 1 ,
.Xr ncurses 3
.Sh AUTHORS
.An Ryan Flannery Aq Mt ryan.flannery@gmail.com .
